# -*- coding: utf-8 -*-
"""TUGAS7-Simulasi Pemodelan

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X8UJhW0gUS6Bkow6neGGmi4F1uDBBAu_

Skrip Code Python Simulasi Antrian Bank
"""

import numpy as np

def simulasi_antrian_bank(lambda_rate, mu_rate, waktu_simulasi):
    # Inisialisasi variabel
    waktu_tunggu = []  # Menyimpan waktu tunggu setiap pelanggan
    waktu_selesai = []  # Menyimpan waktu selesai pelayanan
    waktu_antri = []  # Menyimpan waktu dalam antrian

    waktu_kedatangan = 0
    waktu_pelayanan = 0
    waktu_sekarang = 0
    pelanggan_dalam_sistem = 0

    # Proses simulasi antrian
    for i in range(1, waktu_simulasi + 1):
        # Kedatangan pelanggan (Poisson process)
        waktu_kedatangan += np.random.exponential(1 / lambda_rate)

        # Update waktu saat ini jika kedatangan pelanggan lebih lambat dari waktu_sekarang
        if waktu_kedatangan > waktu_sekarang:
            waktu_sekarang = waktu_kedatangan

        # Waktu pelayanan (Exponential distribution)
        waktu_pelayanan = np.random.exponential(1 / mu_rate)

        # Waktu tunggu pelanggan (jika ada pelanggan yang sedang dilayani)
        if pelanggan_dalam_sistem > 0:
            waktu_tunggu.append(waktu_sekarang - waktu_kedatangan)
            waktu_antri.append(waktu_sekarang - waktu_kedatangan)

        # Pelayanan pelanggan selesai
        waktu_selesai.append(waktu_sekarang + waktu_pelayanan)

        # Update waktu sistem dan jumlah pelanggan dalam antrian
        waktu_sekarang += waktu_pelayanan
        pelanggan_dalam_sistem += 1

    return waktu_tunggu, waktu_selesai, waktu_antri

# Parameter untuk simulasi
lambda_rate = 5  # Kedatangan pelanggan per menit
mu_rate = 6      # Kecepatan pelayanan teller (pelanggan per menit)
waktu_simulasi = 1000  # Jumlah simulasi yang dilakukan

# Jalankan simulasi
waktu_tunggu, waktu_selesai, waktu_antri = simulasi_antrian_bank(lambda_rate, mu_rate, waktu_simulasi)

# Menghitung statistik dari hasil simulasi
rata_waktu_tunggu = np.mean(waktu_tunggu)  # Rata-rata waktu tunggu pelanggan
rata_waktu_antri = np.mean(waktu_antri)    # Rata-rata waktu di antrian
rata_waktu_dalam_sistem = np.mean(waktu_selesai) - np.mean(waktu_tunggu)  # Waktu rata-rata dalam sistem (waktu tunggu + waktu pelayanan)

# Outputkan hasil simulasi dalam format teks
print("Hasil Simulasi Antrian di Bank:")
print("---------------------------------")
print(f"1. Rata-rata waktu tunggu pelanggan dalam antrian: {rata_waktu_tunggu:.2f} menit")
print(f"2. Rata-rata waktu pelanggan di antrian: {rata_waktu_antri:.2f} menit")
print(f"3. Rata-rata waktu pelanggan dalam sistem: {rata_waktu_dalam_sistem:.2f} menit")
print(f"4. Total pelanggan yang dilayani: {len(waktu_tunggu)} pelanggan")